spring.application.name=SpringBoot-MVC-2-Practice-1
spring.datasource.url=jdbc:mysql://localhost:3306/6March
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.view.suffix=.jsp